spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: itMeteor=521314
    url: jdbc:mysql://47.106.38.176:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: itmeteor
    password: Meteor=12345
    host: 47.106.38.176
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 47.106.38.176
    database: 0
    port: 6379
    password: Meteor=12345
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/